---
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "00:10"
      timezone: "Asia/Calcutta"
    versioning-strategy: widen
    target-branch: "main"
    labels:
      - "🌱root"
      - "🤖dependabot"

  - package-ecosystem: "npm"
    directory: "/packages/cli"
    schedule:
      interval: "weekly"
      time: "00:10"
      timezone: "Asia/Calcutta"
    versioning-strategy: widen
    target-branch: "main"
    labels:
      - "📦packages"
      - "🤖dependabot"

  - package-ecosystem: "npm"
    directory: "/packages/core"
    schedule:
      interval: "weekly"
      time: "00:10"
      timezone: "Asia/Calcutta"
    versioning-strategy: widen
    target-branch: "main"
    labels:
      - "📦packages"
      - "🤖dependabot"

  - package-ecosystem: "npm"
    directory: "/packages/config"
    schedule:
      interval: "weekly"
      time: "00:10"
      timezone: "Asia/Calcutta"
    versioning-strategy: widen
    target-branch: "main"
    labels:
      - "📦packages"
      - "🤖dependabot"

  - package-ecosystem: "npm"
    directory: "/packages/utils"
    schedule:
      interval: "weekly"
      time: "00:10"
      timezone: "Asia/Calcutta"
    versioning-strategy: widen
    target-branch: "main"
    labels:
      - "📦packages"
      - "🤖dependabot"
