🌱root:
  - '*'

📝docs:
  - docs/**/*
  - packages/**/README.md
  - README.md

🐚shell:
  - *.sh*

☁︎ci:
  - .github/*

🧪test:
  - packages/**/test/*

📦packages:
  - packages/**/*

📜scripts:
  - scripts/*

🔌third_party:
  - third_party/**/*
