📝docs:
  - 'docs/**/*'
  - '**/README.md'

🐚shell:
  - '*.sh*'

☁︎ci:
  - .github/**/*

🧪test:
  - 'tests/**/*'
  - '**/tests/**/*'
  - '**/__tests__/**/*'

📦packages:
  - 'packages/**/*'

🔌third_party:
  - 'third_party/**/*'
