image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install Dependencies
    init: pnpm install

vscode:
  extensions:
    - "davidanson.vscode-markdownlint"
    - "eamodio.gitlens"
    - "editorconfig.editorconfig"
    - "esbenp.prettier-vscode"
    - "folke.vscode-monorepo-workspace"
    - "foxundermoon.shell-format"
    - "zixuanchen.vitest-explorer"
    - "seatonjiang.gitmoji-vscode"
    - "streetsidesoftware.code-spell-checker"
