image:
  file: config/.gitpod.Dockerfile

tasks:
  - name: Install Dependencies
    init: pnpm i --no-frozen-lockfile

vscode:
  extensions:
    - aaron-bond.better-comments
    - codecov.codecov
    - davidanson.vscode-markdownlint
    - eamodio.gitlens
    - editorconfig.editorconfig
    - folke.vscode-monorepo-workspace
    - foxundermoon.shell-format
    - seatonjiang.gitmoji-vscode
    - zixuanchen.vitest-explorer
