---
name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:

  pr:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: thehanimo/pr-title-checker@v1.4.0
        with:
          pass_on_octokit_error: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  trivy_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: .
          scan-type: fs
          scan-ref: .
          output: dependency-results.sbom.json
          github-pat: ${{ secrets.GITHUB_TOKEN }}

  triage:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/labeler@v4

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node

      - name: 👷 Build
        run: |
          nr -r ci:env-copy
          nr build
          nr -r ci:env-delete
          nr -r build:check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node

      - name: 👕 Lint
        run: nr lint

  e2e_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node

      - name: 👷 Build
        run: nr build

      - name: 🌐 E2E test
        run: pnpm -C apps/web test:e2e

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: artifacts/e2e/reports
          retention-days: 30

  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node_version: [18]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
        with:
          node-version: ${{ matrix.node_version }}

      - name: 🧪 Unit Test
        run: nr test:ci

      - name: 📚 Storybook build
        run: nr -C packages/ui build:storybook

      - name: 🚨 Storybook test
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          pnpm -C packages/ui test:storybook:ci

  action-timeline:
    needs: [build, e2e_test, lint, pr, test, trivy_scan, triage]
    runs-on: ubuntu-latest
    steps:
      - uses: Kesin11/actions-timeline@v1
