name: First Interaction

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  check-for-first-interaction:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@master
      - uses: ./.github/actions/setup-node
      - name: Install
        run: pnpm i --no-frozen-lockfile
      - uses: actions/first-interaction@main
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            Hello! Thank you for filing an issue.
            If this is a bug report, please include relevant logs to help us debug the problem.
          pr-message: |
            Hello! Thank you for your contribution.
